### ISSUE TITLE
An easy way to switch the plot class of an element

### ISSUE THREAD

**Issue by jlstevens** [pyviz/holoviews#115]
Right now the `Store` holds the association between the elements and their corresponding plotting classes. This has worked well so far but you can imagine having several radically different plotting styles for the same `Element`. Admittedly I can't think of any good examples right now but it is certainly feasible!

In general, we only want to define new elements when there is a compelling semantic meaning to assign to the data  and _not_ just because you want to plot the same data slightly differently (that said, you could argue that `Scatter` and `Curve` is such a distinction - but that is a very common case).

You can already change the association by directly working with Store but you can actually imagine making the plotting class into a plot option. This would work as the display hooks have access to the `Store` and all the options even before the element is dispatched to a particular plotting class. In particular I can imagine something like this:

``` python
%%opts Image [plot_class='FancyImagePlot']
```

This would then dispatch any `Image` elements in that cell to the `FancyImagePlot` class instead of the normal `RasterPlot`. Obviously, there would have to be a way for the plot classes to ignore the the `plot_class` option (maybe just a parameter on Plot with negative precedence?).

 I can also imagine this would be useful for external developers writing their own custom plotting classes.

**Comment by jbednar** [comment]
I think it would be good to wait for a very specific use case, keeping the above possibility in mind, to guide us to the correct implementation.

As an aside, I'm wondering if Scatter and Curve really do have the same semantics.  How will they handle multiple y values for the same x value?  Presumably that's no problem for Scatter.  For Curve, can you e.g. specify a circle by listing the right points, in order, even if it ends up wrapping back on itself?  Either way it's worth pointing out what will happen, in the Elements tutorial.

**Comment by jlstevens** [comment]
> For Curve, can you e.g. specify a circle by listing the right points, in order, even if it ends up wrapping back on itself? 

You can do that right now but it isn't recommended, namely because if index along the x-axis, we only return the first value (i.e we assume curves are functions). In fact scatter will have exactly the same issue: I think the elements that you would want for non-functions (i.e one-to-many relationship from the x-axis) are ``Points`` and ``Path``.

**Comment by jbednar** [comment]
Hmm.  I can't see any statement explicitly in the literature that a scatterplot should itself be a function (even if it is expected to correspond to one in reality, with some error).  A Google Image Search for "scatterplot" pulls up numerous examples that clearly have multiple datapoints per x value.  I personally would expect to be able to take many measurements at the same x value and put them all into the same scatterplot, so I don't think people will expect that our Scatter class will in any way rely on having one y value per x value.

Maybe we can explicitly state that the Scatter and Curve classes will both work fine with multiple y values for the same x, but that the indexing operations they support are only likely to be useful in the case of a true function, because which of the ambiguous values will be returned is undefined.  People might even want a flag that they could set to raise an exception if multiple y values are given for a certain x, if they are relying on indexing being meaningful for their object.

**Comment by jlstevens** [comment]
Just a note: since #141 you would also need to specify an associated backend somehow.

This could be inferred from the ``backend`` parameter on the plot classes ``renderer`` attribute.  The issue then is you may have a class called ``RasterPlot`` available for lots of different renderers. 

Two possibilities:

1. You could specify ``[plot_class='mpl.FancyImagePlot']`` but that probably involves the user knowing more about the code structure than necessary.
2. You could assume the ``plot_class``  supplied is associated with the currently active renderer. This is also something you could check and warn about (i.e check that the renderer of the plot matches the active renderer).

On balance, I would go for option 2. whenever we decide to implement it - i.e when we evantually need this feature!

**Comment by philippjfr** [comment]
@jbednar I do agree that Scatter is confusing because it does usually imply it's just a bunch of samples plotted against each other, not necessarily restricted to one dependent and one independent variable. So it could be flexible, supporting either one or two indexable dimensions. In the ``kdims==1`` mode it could assert that there are is only one y-value per x-value. While a Scatter object with two key_dimensions would allow it.

@jlstevens I think option 2. is sensible. I think this system will mostly be useful for incomplete plotting backends, where some Element types can default back to matplotlib. Switching backends in the notebook is pretty straightforward so for everyday use using ``%output backend='bokeh'`` should be fine.

**Comment by jbednar** [comment]
If x and y are both key dimensions, then yes, there can be more than one data point for a given x.  But I'd argue that it's meaningful to have more than one data point for a given x even for only a single key dimension, in some cases, and not meaningful in others.  If e.g. there are 10 possible x values 0..9, and one randomly samples an x and sees what y is found for it, there will be duplicate y values for a given x, and thus it makes no sense to index on x, yet only one key_dimension (x).  It's really a question of what the user intends -- if they intend it to be like a function, then duplicate y values should be illegal, and lookup should be possible.  If they intend it to be like sampling, then duplicate y values should be ok, and lookup should be illegal (or should explicitly return a list of values).  I don't have any suggestion on how to enforce or support either case, though.

**Comment by jlstevens** [comment]
This issue is a bit confused as there are two threads going on:

1. Easily associating a single element (or composite) to different plotting classes (that may be in a different backend).
2. Some unrelated discussion (that started as an aside) about ``Scatter`` and ``Curve`` which should be in a separate issue! ;-p

The main change since we last discussed this is that a single object can now be styled across backends making this suggestion more useful than before. I am starting to move back in favor of something like ``[plot_class='mpl.FancyImagePlot']`` though:

1. Maybe if the backend is specified, we could automatically switch the backend of a single object without having to use the ``%%output`` cell magic every time?
2. You don't need to specify the backend e.g ``[plot_class='FancyImagePlot']`` means 'use ``FancyImagePlot`` as long as it is available on the current backend'. This reduces to the original suggestion.

If you like this idea, I would remove ``backend`` from the ``%%output`` cell magic and only leave it in the line magic. Then you can either set the backend globally (line magic) or locally for one option (``plot_class`` plot option).

I think this would be quite nice to avoid ``%%output`` spreading everywhere. You can also imagine a precedence between backends such that if ``'FancyPlot'`` isn't available in the current backend, you go through the backends by precedence order until you find that class.

**Comment by philippjfr** [comment]
I don't think this is an idea we want to support anymore do we? Switching out the plotting class using ``Store.register`` is easy enough but if you think switching out the plot for a single cell is important we could still consider what you suggested.

**Comment by jlstevens** [comment]
I still think it is a valid idea, just not something we need to do right away. We haven't yet come across a situation where one element needs two representations that you need to easily switch between. So I think this is still a valid proposal, just not one we need to address at this time.

**Comment by philippjfr** [comment]
Open issues impose a large maintenance cost on my time at this point and make it difficult for me to prioritize more important issues. Since this hasn't come up once since the start of the project I'm closing this.
