### ISSUE TITLE
HoloMap wrongly renders missing data 

### ISSUE THREAD

**Issue by wjaskowski** [pyviz/holoviews#1677]
```python
def sine_curve(phase, freq):
    xvals = [0.1* i for i in range(100)]
    return hv.Curve((xvals, [np.sin(phase+freq*x) for x in xvals]))

phases      = [0, 1, 2]
frequencies = [0.5, 1.0, 1.5]
curves = {(p,f):sine_curve(p,f) for p in phases for f in frequencies}
del curves[0, 1.0]
hmap = hv.HoloMap(curves, kdims=['phase', 'frequency'])
hmap
```
for [0, 1.0] (which is missing) renders the same as for the one previously seen (here: [0, 1.5]) while it should render an empty plot.

Screenshots: 
- https://www.dropbox.com/s/v2r6jov9en8fupp/Screenshot%202017-07-04%2020.23.24.png?dl=0
- https://www.dropbox.com/s/6rrsg8101d27c68/Screenshot%202017-07-04%2020.23.36.png?dl=0

**Comment by philippjfr** [comment]
Thanks, and sorry for not replying sooner. This is a somewhat tricky problem because HoloMaps only serialize plots for which there is available data, so when you hit a key that doesn't have data available there is nothing that will make the set the renderers to be invisible. My proposal therefore is that along with the data for all available keys the widgets additionally send the data for an empty frame, which will be shown whenever the widgets encounter a key that is missing.

**Comment by wjaskowski** [comment]
+1. Empty is definitely better than some random copy.
