### ISSUE TITLE
X-axis gets shrunk when using datashade + matplotlib

### ISSUE THREAD

**Issue by jordansamuels** [pyviz/holoviews#1827]
It appears that using the matplotlib backend causes datashader to shrink the x axis.  

Repro:

Setup cell:
```python
import holoviews as hv
import pandas as pd
import numpy as np
from holoviews.operation.datashader import datashade
hv.extension('matplotlib')
hv.extension('bokeh')
n=1_000_000
df = pd.DataFrame({'x1': np.random.randn(n), 'x2': 10*np.random.randn(n), 'y': 10*np.random.randn(n)})
```

Failure cell:
```python
%%output backend='matplotlib'
datashade(hv.Scatter(df, kdims=['x1', 'y']))
```

This results in 
![image](https://user-images.githubusercontent.com/610909/29729479-ed26947a-89a1-11e7-8ac6-50d723bdeb2d.png)

Using bokeh, it's fine:
```python
%%output backend='bokeh'
datashade(hv.Points(df, kdims=['x1', 'y']))
```

![image](https://user-images.githubusercontent.com/610909/29729490-fd341964-89a1-11e7-81f0-f2920bd40050.png)

If we use `kdims=['x2','y']` with either matplotlib or bokeh, it's fine (similar to proper, second image above).

We can work around this with 
```python
%%opts RGB [aspect='auto']
```

and maybe that's good enough, but it's a bit confusing that this is only necessary for the combination of datashader + matplotlib, and not for any of the other 3 combination in the cartesian of shade/no-shade X backends.

**Comment by jbednar** [comment]
Sorry; looks like I never replied to this, though I meant to!  

There's a lot that goes on for sizing, and unfortunately it does differ between the plotting extensions. I'd love it if they behaved the same, but don't personally know how to make that happen.

One thing to know is that Bokeh supports querying the plot to find out what size it's ended up being. 
We use that for datashader by drawing one initial version at the pixel size provided to the datashade() operator, and then once the whole plot is created and queryable we redraw the datashader plot to match whatever size that is.  This is a very handy feature for the Bokeh backend, helping to hide some of the complexities of what datashader is doing. 

For matplotlib, there's no such mechanism, and so whatever default size is used for datashader becomes the size that's created.

But here, as far as I can see you're just being bitten by the usual Matplotlib default of having equal scaling on both axes, which makes sense when the axes are something approximating Euclidean space, but not otherwise.  I'd be in favor of normalizing the behavior of the backends in this respect, but @philippjfr doesn't think it's possible in any straightforward way, and I don't know the details.

**Comment by philippjfr** [comment]
I'm going to close this, this is not specific to datashade operations, simply to the RGB/Image elements and aspect/sizing consistency is already the subject of several other issues.
