### ISSUE TITLE
Image: DataError or ValueError when passing tuple of kdims.

### ISSUE THREAD

**Issue by mforbes** [pyviz/holoviews#2092]
The following code works as expected:

```python
a = np.arange(10)[:, None]
b = a.T
z = a**2 - b**2
hv.Image((a.ravel(), b.ravel(), z), ['a', 'b'])
```

but changing the second argument to a tuple breaks the code with a very strange message:

```python
a = np.arange(10)[:, None]
b = a.T
z = a**2 - b**2
hv.Image((a.ravel(), b.ravel(), z), ('a', 'b'))
```
```python
...
ValueError: kdims: list length must be between 2 and 2 (inclusive)
```

And if `a` and `b` have different length one gets instead

```python
...
DataError: None of the available storage backends were able to support the supplied data format.
```
Although inspection of the documentation indicates that `kdims` should indeed be a List, my expectation was certainly that a tuple and a list would serve the same role here.

**Comment by jlstevens** [comment]
I believe this is because you can specify a *single* dimension as a tuple of ``(name, label)`` e.g you could use ``('a', "This is the dimension I called 'a'")`` and that would be a single dimension. In your example, it thinks you supplied a single dimension with a name of ``'a'`` and a label of ``'b'``.

This is an unfortunate side-effect of supporting this tuple format for dimensions, combined with the new option of supplying kdims by position couples with allowing individual kdims to be supplied without being forced to pack them into a  list. It means that lists and tuples will behave differently as you have reported!

The only solution I see here is better error reporting to make it clearer that such tuples are seen as a single dimension as opposed to as a pair of dimensions.

**Comment by philippjfr** [comment]
Not sure we can even do that consistently. In this particular case this errored because it was expecting two kdims but in other cases it would simply have accepted the tuple as a single kdim. Would have to think about what we can do to improve this.

**Comment by jbednar** [comment]
We should at least make a big deal of it needing to be a list when we introduce this in the documentation, not that it would help existing users...

**Comment by philippjfr** [comment]
Our user guides describe how to annotate the data with dimensions in detail and there are multiple examples of using tuples for names/labels, so I think this is sufficiently documented now.

**Comment by neighthan** [comment]
I was just struggling with this issue for a bit before I came across an example and remembered the list vs tuple distinction. I don't know if the docstrings are purposefully as succinct as possible, but it would make sense to me to say something about the format of `kdims` in the docstring itself. Currently it just says `kdims:    The key dimension(s) of a Chart represent the independent variable(s).`. If there isn't a real reason to be succinct here, one could add that a list *must* be used for multiple kdims (and possibly also how tuples are used, though I find it harder to say that in a clear way in one sentence. A tuple `(name, label)` can be given to use a separate name for accessing the dimension than the label used in the plot?).

**Comment by philippjfr** [comment]
@neighthan No good reason, there should be an issue somewhere to explain the constructors better in element docstring but I can't find it now. A PR to improve things even if it's just for one element would be appreciated.
