### ISSUE TITLE
problem with hv.extension('bokeh')

### ISSUE THREAD

**Issue by rockkyyao** [pyviz/holoviews#2432]
Hi,
I try to use bokeh in holoviews. But using hv.extension('bokeh') gives the following error:

WARNING:root:notebook_extension: Holoviews bokeh extension could not be imported, it raised the following exception: ImportError('cannot import name 'convert_datetime_array'')

Does anyone know how to fix it?

Thanks!

**Comment by philippjfr** [comment]
Try upgrading to bokeh 0.12.14.

**Comment by rockkyyao** [comment]
Thx!

**Comment by jlstevens** [comment]
I note that we don't currently pin bokeh in the ``environment.yaml``. In an ongoing datashader PR, the [meta.yaml](https://github.com/bokeh/datashader/blob/04b1a0ad5223104c96b23c503e70ffad9871b6db/conda.recipe/base/meta.yaml) gets its dependencies from ``setup.py``. I wonder if ``setup.py`` could get its dependencies from the ``environment.yaml`` so there is only one place to pin things? I do think it would be nice to have fewer places to worry about dependency pinning...

**Comment by jbednar** [comment]
@jlstevens, that's a discussion to have with @ceball, preferably soon; he's worked out a way to have a single source of truth for all such dependencies, and environment.yml isn't very good as that source, because it doesn't allow you to distinguish between the different categories of dependencies involved (e.g. core dependencies, that should be in meta.yml and thus don't need to be/shouldn't be in the envt file. test dependencies (also probably not needed in the envt file), etc.

**Comment by YoungrakSon** [comment]
the kaggle server raise the exception also..

**Comment by YoungrakSon** [comment]
'www.kaggle.com' is just a place where people upload their Data science results.  
In order to upload and present it on the website, .ipynb files have to be run on the kernel of the Kaggle. 
While running my .ipynb file on the kaggle kernel to upload it, I figured out hv.extension('bokeh') is raising the exception on the kernel. The script ran seamlessly on my local laptop.

I have already asked kaggle support team about the error but it haven't been solved yet..

I just wished someone wandering around the internet might see the comment I wrote and contribute to make some progresses on it
Since, the Holoviews is one of my favorite libraries and half of my .ipynb files are visualized with it, and I just can't upload it on kaggle, it led me to write the comment here. I was just looking for a way to solve it myself.

This is not an issue with the Holoviews so this might be a disturbance for you. sorry for that.

**Comment by philippjfr** [comment]
@YoungrakSon Thanks for the kind words. I have used kaggle in the past, I just didn't know they now provided a notebook environment to work in. We have made some recent changes to the way things are displayed in the notebook and it is possible that Kaggle uses outdated IPython/notebook versions which are not compatible with this new approach.

**Comment by YoungrakSon** [comment]
oh I see, There is an update. I think kaggle will soon handle the problem. 

Thank you!

**Comment by philippjfr** [comment]
Don't think there's much we can do here, closing.
