### ISSUE TITLE
hv.Bars Grid Layout in Bokeh and Matplotlib Display Incorrectly

### ISSUE THREAD

**Issue by TylerTCF** [pyviz/holoviews#2642]
Unsure if this is a bug that was captured in the other matplotlib bar chart work in 2017, but I have a simple hv.Dataset with Year, Region, and Type as key dimensions and Count as values.  I used:

```

%%opts Bars [height=300 width=300 xrotation=90 stack_index=1 tools=['hover'] show_grid=True]
#used a random pandas dataframe for the categories and other data in columns
#dtypes (Year=int, Type=string, Region=string, Count=int)
dimensions=['Year', 'Type', 'Region']
values=['Count']
macro=hv.DataSet(data, dimensions, values)
macro.to.to(hv.Bars, ['Year','Type'], ['Count']).grid()
```

I tested both the matplotlib and bokeh backends.  I noticed two problems.  

1. The matplotlib opts don't seem to work for height, width, etc. in the bar element
2. In the grid layout (both backends), the y-axis major and minor tick labels have disappeared.

**Comment by philippjfr** [comment]
Sorry we never replied here. This turns out to be a usage question.

1. matplotlib does sizing very differently to bokeh, so width/height aren't supported, instead size is controlled using fig_size.
2. A grid layout is for comparing the general shape of the data, if you need to compare the values set ``.opts(shared_xaxis=True, shared_yaxis=True)`` to get the axis scales back.
