### ISSUE TITLE
`color` option does not work

### ISSUE THREAD

**Issue by StrausMG** [pyviz/holoviews#3559]
Hi! The code below produces two plots colored in the default blue. Am I missing something?
```python
# cell 0
import holoviews as hv
import numpy as np
from holoviews import opts as ho
hv.extension('bokeh')

# cell 1
hv.Distribution(np.arange(100)).opts(color='green')

# cell 2
hv.Distribution(np.arange(100)).opts(ho.Distribution(color='green'))
```

macOS: 10.14.3
HoloViews: 1.11.3
NumPy: 1.16.2
Bokeh: 1.0.4
JupyterLab: 0.35.4

**Comment by ea42gh** [comment]
Try
`hv.Distribution(np.arange(100)).opts(fill_color='green', line_color='red')`

**Comment by jbednar** [comment]
Usually 'color' is an alias for setting both the fill and line colors, so I'm surprised this doesn't work.

**Comment by philippjfr** [comment]
The problem here is the default definition, ``color`` only works as an alias if no explicit fill or line color are specified but since the default defines both it ends up having no effect:

```python
options.Distribution = Options(
    'style', fill_color=Cycle(), line_color='black', fill_alpha=0.5,
    muted_alpha=0.2
)
```

There are a number such issues which should be addressed. In this case I would suggest changing ``fill_color=Cycle()`` to ``color=Cycle()``. This will make sure that color will work as an alias for fill_color.

**Comment by StrausMG** [comment]
I got it. Thank you all for the answers!

**Comment by philippjfr** [comment]
Thanks for closing, but this is definitely a bug and should be fixed.
