### ISSUE TITLE
Setting opts with Options without a spec errors 

### ISSUE THREAD

**Issue by philippjfr** [pyviz/holoviews#3569]
This code breaks with a pretty useless error:

```python
opts = hv.opts(width=100)
(hv.Curve([1, 2, 3]) * hv.Curve([1, 2, 3])).opts(opts)
```
```
~/development/holoviews/holoviews/util/__init__.py in _expand_options(cls, options, backend)
    335 
    336         for objspec, options in options.items():
--> 337             objtype = objspec.split('.')[0]
    338             if objtype not in backend_options:
    339                 raise ValueError('%s type not found, could not apply options.'

AttributeError: 'NoneType' object has no attribute 'split'
```

The behavior I had assumed was implemented here is that an Options object without a spec would use the spec of the object it is applied to.

**Comment by jlstevens** [comment]
For container types, I think an explicit spec is always clearest and safest. Given that the behavior of `hv.opts` without a spec is a dubious as it is, I did not consider implementing this behavior a priority (in fact it didn't even occur to me). 

I don't particularly like the implicit behavior much but I suppose that it should be implemented for consistency with what happens when you supply keywords only.
