### ISSUE TITLE
Wrong placement of plot in Jupyterlab

### ISSUE THREAD

**Issue by Gerenuk** [pyviz/holoviews#3625]
Currently (holoviews 1.11.3, jupyter 4.4.0) the Bokeh plots of Holoviews in Jupyterlab appear at incorrect positions. At the same time plain Bokeh plots work just fine (jupyterlab_bokeh extension installed but same effect without it).

If you plot with Holoviews in Jupyterlab the plots become just floating canvas above your notebook which never disappear. Not even when you close the notebook.

If you do a plain Bokeh plot before plotting with Holoviews, then Holoviews plots get appended to the Bokeh cell's output, even though it is a completely different cell.

**Comment by jbednar** [comment]
I'm pretty sure this was reported before, but I can't seem to locate the issue now.  At that time I *believe* the issue was either not ever having run `jupyter labextension install @pyviz/jupyterlab_pyviz` or else not running `hv.extension('bokeh')` in your session. Both are needed in any case, so if you haven't done one of those, try it!

**Comment by philippjfr** [comment]
This is definitely down to old versions of HoloViews and the lack of the jupyterlab_pyviz extension being installed.
