### ISSUE TITLE
Dynamically set marker size on Scatter plot

### ISSUE THREAD

**Issue by h2oworker** [pyviz/holoviews#3635]
I am trying Holoviews by recreating the Scatter economic example [holoviews.org/gallery/demos/bokeh/scatter_economic.html](url)

Except for the marker size and the padding, I got the example to work on Holoviews version 1.10.4. So, 

##### How to set marker sizes based on the `Unemployment`?

`dim` does not work in 1.10.4 so this did not work:  ``size=dim('Unemployment`)*1.5`` .  `hv.Dimension` also did not work in 1.10.4

##### How to set padding? And, a related question, what is the correct way to set options? Is it `options` or `opts`? 

Using `options` seems to work in 1.10.4 (`opts` , which is shown on lot of examples did not work on 1.10.4). Is `options` the preferred way to set options (as shown below)? 

`overlay = gdp_unemp_scatter.overlay('Country').options(legend_position='left', width=800, height=400, show_frame=False)`

Any help will be much appreciated.

**Comment by jbednar** [comment]
Is there a particular reason you want to use 1.10.4?  That release is a year old, and I think there have been 12 full releases since then.  In any case, the current holoviews release is 1.12.1, and holoviews.org will show you  how to use that version, not older ones.  Nowadays we recommend `.opts` over `.options`.  We already have a HoloViews version of that example along with most other Bokeh examples:

http://holoviews.org/gallery/demos/bokeh/scatter_economic.html#bokeh-gallery-scatter-economic

If have to use 1.10.4, e.g. because you're in an airgapped environment with nothing more recent, you should build your own copy of the docs locally and use that. Code you write for 1.10.4 should still work with more recent versions, but not vice versa...

**Comment by h2oworker** [comment]
Thank you will upgrade to the latest version.
