### ISSUE TITLE
hv.QuadMesh with 8196x6000 samples

### ISSUE THREAD

**Issue by ThetomekK** [pyviz/holoviews#3709]
I have to display a spectrogram of audio data and tried that with quadmesh. But it crashes my kernel. Is a maximum data size known with quadmesh? My RAM explodes.

Data ist stored as a xarray dataarray with time and frequency as dimensions.

Hover functionality would be great.

**Comment by jbednar** [comment]
If you have uniform spacing in both axes, you should normally use `hv.Image`, which is more efficient than `QuadMesh` while still supporting hover in recent Bokeh versions (1.0+, I think). You can also combine [Datashader](http://holoviews.org/user_guide/Large_Data.html) with HoloViews to handle even larger images, and as long as you use `rasterize()` rather than `datashade()` hover should still work.  If that's still not suitable, we plan to add out-of-core rendering for rasters in Datashader, but we haven't started implementing that yet.

**Comment by ThetomekK** [comment]
Thank you, I'll give hv.Image a try.

**Comment by philippjfr** [comment]
For a 8196x6000 sized array you will definitely want to use the ``rasterize`` operation.

```python
from holoviews.operation.datashader import rasterize
rasterize(hv.Image(...))
```

I'll close since this is a usage question and a raw QuadMesh will never scale to these sizes in bokeh since that's too much data to send to your browser.
