### ISSUE TITLE
Holoview RGB/Image axes get confused when used intermingled with Geoviews objects

### ISSUE THREAD

**Issue by cocoaaa** [pyviz/holoviews#4005]
I've encountered some incompatibilities between holoviews and geoviews objects.

```python
import rasterio as rio
from rasterio.plot import reshape_as_image

rgb_ds = rio.open(rgb_fns[idx])
rgb_bounds = rgb_ds.bounds
rgb_img = reshape_as_image(rgb_ds.read())/255.

mask_ds = rio.open(mask_fns[idx])
mask_bounds = ds.bounds
mask_img = reshape_as_image(mask_ds.read())/255.

hv_rgb = hv.RGB(rgb_img, bounds=rgb_bounds, group='rgb').redim(x='Longitude', y='Latitude')
hv_mask = hv.Image(mask_img, bounds=mask_bounds, group='mask').redim(x='Longitude', y='Latitude')


gdf_edges is a geopandas.DataFrame object with `geometry` of type `LINESTRING`
gv_osm = gv.Path(gdf_edges)


#Okay
#gv_osm

#Okay
#hv_rgb + hv_mask

#Not okay: holoviews objects' xaxis and yaxis get really large
#hv_rgb + hv_mask + gv_osm
```

In fact, this behavior occurs when I plot `hv.RGB` with `gv.Image` objects together:
```
hv_rgb = hv.RGB(rgb_img, bounds=rgb_bounds, group='rgb').redim(x='Longitude', y='Latitude')
gv_mask = gv.Image(mask_img, bounds=mask_bounds, group='mask').redim(x='Longitude', y='Latitude')

display(hv_rgb) #ok
display(gv_mask) #ok
display(hv_rgb + gv_mask) #axes range of holoview object gets confused
```
![image](https://user-images.githubusercontent.com/8037983/65800755-2a89df00-e12c-11e9-9c0b-2d8d71b9d549.png)

---
The reason why I used `hv.RGB` element instead of `gv.RGB` in the first place is because `gv.RGB` was not properly showing the Lat, Lon values upon mouse hover:

```python
import xarray as xr

idx = 1
rgb_da = xr.open_rasterio(rgb_fns[idx])/255.
mask_da = xr.open_rasterio(mask_fns[idx])/255.
r,g,b = map(np.asarray,[rgb_da.sel(band=1), rgb_da.sel(band=2), rgb_da.sel(band=3)])
xs, ys = map(np.asarray, [rgb_da.coords['x']), np.array(rgb_da.coords['y'])])

# Read as gv elements
gv_rgb = gv.RGB((xs,ys,r,g,b), vdims='R G B'.split())
# gv_mask = gv.Image((xs,ys,mask_da.sel(band=1)))
gv_mask = gv.Image(mask_da, kdims=['x','y'])
gv_rgb + gv_mask
```
![image](https://user-images.githubusercontent.com/8037983/65800717-12b25b00-e12c-11e9-97cf-5fd5656c750a.png)

Am I missing something to have the lat lon dimensions mapped correctly from the xarray data array?

Another thing I'd like to share is: 

`gv_rgb = gv.RGB((xs,ys,r,g,b), vdims='R G B'.split())` errors without specifying `vdims`. Quick debugging seems to suggest `gv.RGB` defaults to RGBA (4 channels) instead of considering the number of `vdims` from the input arguments (3 from r,g,b in this case)
 
---
I think it's better to use geoviews objects for all three data, but also think this behavior probably
is not what's intended -- and we'd probably want them to be able to visualize them together?

**Comment by jbednar** [comment]
It's not confused, you are. :-)

Some of the objects you are plotting appear to be in Web Mercator coordinates (with lat,lon values like 3e6) and others are in latitude, longitude (with values like 30 or -30), but all of them have dimensions declared as "Latitude" or "Longitude".  HoloViews and GeoViews wlll try to find a common axis range for the same dimensions occuring in the same plot, but in this case you've provided completely incommensurate data values.  

To resolve the issue, you can unlink the axes by giving them different names or by passing an `axiswise=True` option to each one so that they are normalized independently.  But it's probably better to make them all have consistent values.  Using GeoViews consistently, declaring the `crs` each time, will make sure that happens.  Or you can do it manually, making sure that your HoloViews object is converted into the right units yourself.  But one way or another, if you display incommensurate units normalized together, it isn't going to work.

(If you want to discuss the second issue about split, please open a separate issue, as it's unrelated to this one.)

**Comment by cocoaaa** [comment]
Thank you, it's certainly true that I'm confused:).  Currently, all the underlying data are read from the same file (whether I pass it along to geoviews or holoviews elements), and all coordinate information is in the epsg4326 crs (lat/lon). For instance, 
```python
#hv
print(hv_rgb.bounds)
#BoundingBox(points=((-115.1636076,36.2160476999),(-115.1600976,36.2195576999)))

# gv
print(xs)
#array([-115.16360625, -115.16360355, -115.16360085, ..., -115.16010435,
       -115.16010165, -115.16009895])

print(gv_rgb.bounds)
#BoundingBox(points=((-115.1636076,36.2160476999),(-115.1600976,36.2195576999)))
```
I'm still not sure where the incongruency of the underlying data's units may come from. 

Another (maybe related) question is why the gv.RGB's Lat, Lon values appear as NaN s on mouse hover. 
![image](https://user-images.githubusercontent.com/8037983/65806326-dd166d80-e13d-11e9-9a89-d992d7aa2752.png)

I'd appreciate your insights!:) Thank you.

**Comment by jbednar** [comment]
>holoviews' plot considers its data to be in Web Mercator CRS, whereas geoviews' plot considers them to be in EPSG4326 (or an input argument to crs keyword, if specified). So, even though the underlying data values are in the same scale, when they are plotted, the interpretations are different.

Almost -- yes, the values when plotted are different, but it's the other way around. HoloViews provides general-purpose plotting and doesn't make any assumptions about your data's units; it doesn't know anything about geographic coordinate systems at all.  So HoloViews will never convert between any geographic coordinate system.  GeoViews, on the other hand, expects data to be provided in PlateCarree/lat-lon/EPSG4326/wgs84 unless otherwise specified with `crs=`, and then reprojects it as needed for the particular display context, while always labeling the axes with standard lat,lon units regardless of what projection is actually displayed.  To work well with map tile servers, it looks like GeoViews is defaulting to Web Mercator output (which is what was confusing you!), which is fine as long as you only use GeoViews objects.  But a Web Mercator plot won't work well with a HoloViews plot with the same dimension names, because even though the axis labels, etc. look like lat/lon, the actual plot is in Web Mercator, with its incommensurate units.

If you don't need to use tile maps and want to combine with HoloViews objects, then you can explicitly tell GeoViews that the output projection should be lat/lon (`projection=ccrs.PlateCarree()`, I think). And if you never want any projection, just use HoloViews objects for everything.  But mixing and matching like you were doing will make you very confused!

As for hover, as I said, that's a separate issue, so please search existing issues to see if that's been reported (I think it has), and report it separately if not.  Each Github issue should be about one thing that can be addressed and closed separately from any other thing.

**Comment by philippjfr** [comment]
Thanks for explaining that @jbednar. This is all covered in the [GeoViews documentation](http://geoviews.org/user_guide/Projections.html). If you think that documentation isn't very clear please file an issue or PR to improve it, but I'll close this issue because it is about GeoViews not HoloViews and mostly a usage question.
