### ISSUE TITLE
Font size options

### ISSUE THREAD

**Issue by jlstevens** [pyviz/holoviews#608]
Currently fontsizes can be specified either as a single number (fixed in #607) or as a dictionary for finer control. A numeric value is in pt (inherited from matplotlib) and the keys you can specify are:  'xlabel','ylabel', 'labels', 'ticks', 'title', 'legend', 'legend_title'.

This system has worked so far but there are times when it can be cumbersome. For instance, using the output magic to double the figure size by 200% makes the figure bigger as request but the font sizes stay the same size as they are in pt. Having to use all the keys listed above to make the text correctly sized relative to everything else is awkward. Maybe there should also be a separate issue to scale the default font sizes when the figure size changes?

Maybe we could support strings such as '2.5x' as a multiplier of the defaults or '2.5pt' to make the units explicit. The Bokeh backend could then support other units such as '2.5px' and '2.5em'. Using strings this way could help us retain backwards compatibility.

Lastly it is worth mentioning that specifying a numeric value for the fontsize doesn't affect the tick label size. Is this still the behaviour we want?

**Comment by philippjfr** [comment]
Overall I agree with your suggestion, allowing string based font specifications is probably the way to go. I also like the idea of optionally scaling font size with the figure size although in practice it may be difficult to get right. I also wouldn't scale font size with figure size by default because often I increase the font size specifically to reduce font sizes relative to the figure, otherwise I usually just increase the ``dpi``.

>Lastly it is worth mentioning that specifying a numeric value for the fontsize doesn't affect the tick label size. Is this still the behaviour we want?

It's inconsistent and confusing but scaling tick labels with everything else is also potentially annoying because you usually don't want tick labels to be the same size as everything else. I'd be okay with keeping the current behavior, but could be persuaded otherwise.

**Comment by jbednar** [comment]
> often I increase the font size specifically to reduce font sizes relative to the figure, otherwise I usually just increase the dpi

I think we need a section in the docs about setting plot and text sizes, because it's hard to see how ordinary users would figure this out otherwise...

**Comment by philippjfr** [comment]
>I think we need a section in the docs about setting plot and text sizes, because it's hard to see how ordinary users would figure this out otherwise...

I think a general Tutorial about setting common plot options like axes, ticks, font sizes, legends etc. might be a good idea.

**Comment by jbednar** [comment]
Definitely.

**Comment by philippjfr** [comment]
This is documented in http://holoviews.org/user_guide/Customizing_Plots.html#Font-sizes
