### ISSUE TITLE
Add explicit documentation for the output magic

### ISSUE THREAD

**Issue by philippjfr** [pyviz/holoviews#63]
We have no real breakdown of the different widget types, backend options, figure types etc.. We should probably add a Tutorial notebook to explain how to select different backends and what trade-offs they have compared to each other.

**Comment by jbednar** [comment]
Yes.  It would probably be good for such a tutorial to talk about how easy or difficult it is to add new backends, and roughly how to do so, to encourage people with a special interest in some particular backend to build it themselves.

**Comment by jlstevens** [comment]
I've updated the comment to say this issue is explicitly about documenting the output magic. I think the options tutorial would be a good place for this.

Jim's suggestion about documenting how to add backends is a good one but I think that can go in a separate issue. I think that explicitly saying something about the size, fig, holomap and backend options is a higher priority right now.

**Comment by philippjfr** [comment]
Thanks, basically it has to explain that the output magic sets options depending on the backend, and how figure formats, sizing and widget types relate to that.

**Comment by jbednar** [comment]
Providing documentation for how to add a new backend does seem out of scope for such a tutorial.  

As for whether is an "output magic tutorial", I was very careful when making the Options tutorial to introduce all concepts using pure Python initially, so that it was clear that %%opts was not ever required. How easy it is to do things using %%opts should seem like magic, but what it actually means and represents should be concrete and specific, grounded in Python. So, just as that tutorial was not called the "opts magic tutorial" (even though it covers that), I don't think this proposed tutorial should be called the "output magic tutorial", even though I agree we need such a tutorial and that it should cover what the output magic does.  

By analogy, is this then the "Output" tutorial?  It might then get confused with the Exporting tutorial, though that tutorial already does cover some of what %%output does, so it's a real overlap and not just an accidental one...

**Comment by philippjfr** [comment]
This will be the Renderer tutorial in that case since the output magic mostly controls options on the Renderer classes. It'll mainly be concerned how the Renderer works and discuss how the output magic controls various options on it.

**Comment by jbednar** [comment]
Sounds good.  Still has overlap with Exporting with either title; some material may need to be swapped between that tutorial and this new one.

**Comment by philippjfr** [comment]
We really need this but I'm afraid it won't happen for v1.7 bumping to v1.8, which will focus on documentation.

**Comment by jlstevens** [comment]
I think we could have a quickstart guide in contrib about this before 1.7 but probably not a full tutorial.

**Comment by philippjfr** [comment]
The user guide on Applying Customizations now covers the hv.output utility, the magic is discouraged.
