### ISSUE TITLE
Merging clashing stream parameters by timestamp

### ISSUE THREAD

**Issue by jlstevens** [pyviz/holoviews#847]
As the streams system is currently under development, this issue is a feature request based on the design as we are implementing it now.

Name clashes between stream parameters are currently disallowed entirely but there is another way clashes could be resolved. If we kept track of when parameters are updated, the 'correct' value given multiple possibilities (i.e parameters of the same name) would be to use the most recently updated value. Essentially, we could disambiguate the appropriate value by timestamp.

This would allow multiple stream sources for one parameter. For instance, you could have a crosshair that you can move around using a pair of sliders _or_ by generating the appropriate events by hovering with the mouse. Whichever source generated the most recent event would take precedence.

Even if this were implemented, one issue (illustrated by this example) is that we would want the slider position to then update dynamically. Otherwise, the sliders would be show stale values once the mouse was used to move the crosshair.

**Comment by philippjfr** [comment]
Do we still want this? I've never found I wanted or needed this and from my perspective at least even the premise seems flawed:

>For instance, you could have a crosshair that you can move around using a pair of sliders or by generating the appropriate events by hovering with the mouse.

Couldn't both the slider and the hover events just be connected to the same stream? I'd be in favor of closing this issue, but if you see a good reason to keep it open I won't object.

**Comment by jbednar** [comment]
Connecting both sources of events to a single stream seems like the way this would work cleanly, to me.

**Comment by philippjfr** [comment]
@jlstevens I'll ask again. To me this suggestion seems to solve a non-existent issue. A shared stream that receives events from both sources is the correct way of dealing with this rather than having duplicating streams which then have to be disambiguated. Do you agree? Had you envisioned some other problem? Can I close?

**Comment by jlstevens** [comment]
I don't see why this needs to be closed, as it is marked as a wishlist item and therefore not a priority (and has no associated milestone).

I don't see why the idea is invalidated by anything, it still seems like it could be a nice way to avoid having to rename clashing stream parameters so I'm not sure it is a non-existent issue. Of course you can work around it by renaming but the idea is that this could be an easier approach.

> A shared stream that receives events from both sources is the correct way of dealing with this...

I don't see how that is easier than the timestamp policy. Do you mean you would have to define a new stream class to be triggered by two event sources? If so, that is the sort of work that this proposal would help avoid...

**Comment by philippjfr** [comment]
I still don't understand or follow what is actually being proposed here or what problem it solves in practice. What would actually be disambiguated and why do timestamps solve anything? We already keep track of which stream is doing the triggering so that is already sufficient to disambiguate which one should be used if we did allow clashes.

Personally I feel like allowing clashing stream parameters and resolving them by checking which one is triggering can result in too many implicit behaviors that are not transparent to a user. I'm a solid -1 on this proposal even though it could be easily implemented based on already existing mechanisms.

**Comment by philippjfr** [comment]
Issue has gone stale and streams have worked well for years. I'm closing, please reopen if you feel strongly about this.
